# Application settings
app:
  name: "App Name"
  secret: "app_secret"
  debug: false
  port: 8080

# Database settings
database:
  host: "localhost"
  port: 5432
  name: "db_name"
  user: "db_user"
  password: "db_password"
